belong_system_mapping = {
    "id":"*系统id",
    "system_name":"*系统名称\n(最多50个字符)",
    "department_id": "*所属部门id",
    "department":"所属部门",
    "belonging_department":"所属处室",
    "system_summary":"*系统概述\n(最多200个字符)",
    "run_status":"*运行状态\n(单选:在建、在用、停用)",
    "network":'*网络类型\n(单选:互联网、电子政务外网、电子政务内网、行业专网、电子政务外网和互联网)',
    "build_unit":"*建设单位\n(最多50个字符)",
    "construction_unit":"*承建单位\n(最多50个字符)",
    "service_object":'*使用对象\n(多选:企业、社会公众、部门内部,多个选项之间","隔开,逗号须英文格式的逗号)',
    "build_method":'*建设方式\n(单选:本级建设(或部署)政务信息系统、国家部委部署系统、其他)',
    "system_type":'*系统类型\n(多选:基础设施、数据系统、业务系统、政务服务系统、其他,多个选项之间","隔开,逗号须英文格式的逗号)',
    "investment_total":'*建设费用(万元)\n(正数,最多2位小数)',
    "funds_source":'*资金来源\n(多选:中央资金、省级资金、其他资金,多个选项之间","隔开,逗号须英文格式的逗号)',
    "devops_expenses":'*本年度运维经费(万元)\n(正数,最多2位小数)',
    "person":"*填报人\n(最多20个字符)",
    "phone":"*填报人手机号",
    "notes":"备注\n(最多200个字符)",
    "create_id":"用户id",

}

platform_mapping = {
    "id":"平台id",
    "department_id":"部门id",
    "create_id":"用户id",
    "platform_name":"平台名称",
    "platform_summary":"平台概述",
    "department":"所属部门",
    "belonging_department":"所属处室"
}

dmdb_mapping = {
    'CLOB': '备注型M',
    'VARCHAR': '字符型C',
    'CHARACTER': '字符型C',
    'LONGVARCHAR': '备注型M',
    'CHAR': '字符型C',
    'INT': '数值型N',
    'TINYINT': '数值型N',
    'INTEGER': '数值型N',
    'BIGINT': '数值型N',
    'NUMBER': '货币型Y',
    'DECIMAL':'货币型Y',
    'DEC':'货币型Y',
    'BYTE':'数值型N',
    'SMALLINT':'数值型N',
    'BINARY':'通用性G',
    'VARBINARY':'通用性G',
    'FLOAT':"浮点型F",
    'DOUBLE':'双精度型B',
    'REAL':'双精度型B',
    'DOUBLE PRECISION':'双精度型B',
    'DATE': '日期型D',
    'DATETIME': '日期时间型T',
    'TIME':'日期时间型T',
    'TIMESTAMP': '日期时间型T',
    'BIT': '逻辑型L',
    'LONG':'备注型M',
    'IMAGE':'通用性G',
    'LONGVARBINARY':'通用性G',
    'BLOB':'通用性G',
    'BFILE':'备注型M',
    'TEXT': '备注型M',

}

mysql_mapping = {
    'VARCHAR': '字符型C',
    'CHAR': '字符型C',
    'TINYTEXT':'备注型M',
    'TEXT':'备注型M',
    'MEDIUMTEXT':'备注型M',
    'LONGTEXT':'备注型M',
    'TINYINT':'数值型N',
    'SMALLINT':'数值型N',
    'MEDIUMINT':'数值型N',
    'INT':'数值型N',
    'INTEGER':'数值型N',
    'BIGINT':'数值型N',
    'FLOAT':'浮点型F',
    'DOUBLE':'浮点型F',
    'DECIMAL':'货币型Y',
    'BIT':'逻辑型L',
    'YEAR':'日期型D',
    'TIME':'日期时间型T',
    'DATE':'日期型D',
    'DATETIME':'日期时间型T',
    'TIMESTAMP':'日期时间型T',
    'ENUM':'字符型C',
    'SET':'字符型C',
    'BINARY':'通用性G',
    'VARBINARY':'通用性G',
    'TINYBLOB':'通用性G',
    'BLOB':'通用性G',
    'MEDIUMBLOB':'通用性G',
    'LONGBLOB':'通用性G'
}

pgsql_mapping = {
    'SMALLINT':'数值型N',
    'INTEGER':'数值型N',
    'BIGINT':'数值型N',
    'DECIMAL':'货币型Y',
    'NUMERIC':'货币型Y',
    'REAL':'浮点型F',
    'DOUBLE PRECISION':'双精度型B',
    'SMALLSERIAL':'数值型N',
    'SERIAL':'数值型N',
    'BIGSERIAL':'数值型N',
    'CHAR':'字符型C',
    'VARCHAR':'字符型C',
    'TEXT':'备注型M',
    'CITEXT':'备注型M',
    'BOOLEAN':'逻辑型L',
    'DATE':'日期型D',
    'TIME':'日期时间型T',
    'TIMESTAMP':'日期时间型T',
    'INTERVAL':'日期时间型T',
    'BYTEA':'通用性G',
    'BIT':'通用性G',
    'VARBIT':'通用性G'
}

oracle_mapping = {
    'CHAR':'字符型C',
    'VARCHAR':'字符型C',
    'NCHAR':'字符型C',
    'NVARCHAR':'字符型C',
    'DATE':'日期型D',
    'TIMESTAMP':'日期时间型T',
    'LONG':'备注型M',
    'RAW':'通用性G',
    'LONG RAW':'通用性G',
    'BLOB':'通用性G',
    'CLOB':'备注型M',
    'NCLOB':'备注型M',
    'BFILE':'通用性G',
    'ROWID':'字符型C',
    'NROWID':'字符型C',
    'NUMBER':'数值型N',
    'DECIMAL':'货币型Y',
    'INTEGER':'数值型N',
    'FLOAT':'浮点型F',
    'REAL':'浮点型F',
}

sqlite_mapping = {
    'NULL':'',
    'INTEGER':'数值型N',
    'REAL':'浮点型F',
    'TEXT':'字符型C',
    'BLOB':'通用性G'
}

